# Generated by Django 4.1.5 on 2023-01-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_circuitmaintenance",
            "0001_squashed_0005_alter_circuitmaintenance_options",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="circuitmaintenancenotifications",
            name="email_body",
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="circuitmaintenancenotifications",
            name="email_from",
            field=models.EmailField(max_length=254),
        ),
    ]
