# Generated by Django 4.1.5 on 2023-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_circuitmaintenance",
            "0006_circuitmaintenancenotifications_email_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circuitmaintenancenotifications",
            options={
                "ordering": ("email_recieved",),
                "verbose_name": "Circuit Maintenance Notification",
                "verbose_name_plural": "Circuit Maintenance Notification",
            },
        ),
        migrations.RemoveField(
            model_name="circuitmaintenancenotifications",
            name="provider",
        ),
        migrations.AlterField(
            model_name="circuitmaintenancenotifications",
            name="email_body",
            field=models.TextField(),
        ),
    ]
