# Generated by Django 4.1.5 on 2023-02-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_circuitmaintenance",
            "0007_alter_circuitmaintenancenotifications_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CircuitMaintenancePoller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
